### ISSUE TITLE
Why is Backward.yml  gs_score_function set to 0x104 ?

### ISSUE THREAD

**Issue by PSY222** [nfyfamr/SafeguardGS#1]
Hello, thank you for your well-structured GitHub repository and meticulous experimental approach in your SafeGS paper. I have a quick question regarding the gs_score_function set to 0x104 in the benchmark.yaml. The 0x104 configuration uses cosine similarity. However, in the paper, it was analyzed that the Score13 method, which computes the mean difference between colors subtracted by 1, showed the best performance. Could you please explain the rationale behind this discrepancy?

benchmark.yaml  
`
  safeguard_gs_score_function:
    values: [0x104]`

submodules/diff-gaussian-rasterization/cuda_rasterizer/forward.cu
```
case 0x10:
	for (int ch = 0; ch < C; ch++)
		color_cos_sim += gt_color[ch] * prim_color[ch];
	return score * color_cos_sim

```

**Comment by nfyfamr** [comment]
Hi, @PSY222. Sorry for the confusion. While I was updating the code, I missed it. The correct `safeguard_gs_score_function` corresponding to the score function variant 13 in the paper is `0x24`, which is $(1-mean(||C_{gt}-c_i||_1)) * alpha_i * transmittance_i$.

I also found a miscellaneous error in the CUDA code and updated it. You can pull the latest code and rebuild the `diff_gaussian_rasterization` module in your previously set up conda environment by running the following command:

> pip install --no-cache-dir submodules/diff-gaussian-rasterization

**Comment by PSY222** [comment]
Thank you for sharing updates!
